print('==== Desafio 004 ====')
valorDigitado = input('Digite algo: ')
print('O tipo primitivo desse valor é', type(valorDigitado))
print('O valor digitado só tem espaço ?', valorDigitado.isspace())
print('O valor digitado é um número ?', valorDigitado.isnumeric())
print('O valor digitado é alfabético ?', valorDigitado.isalpha())
print('O valor digitado é alfanumérico ?', valorDigitado.isalnum())
print('O valor digitado está em maiúsculas ?', valorDigitado.isupper())
print('O valor digitado está em minúsculas ?', valorDigitado.islower())
print('O valor digitado está capitalizada ?', valorDigitado.istitle())
